### ISSUE TITLE
injection des data

### ISSUE THREAD

**Issue by MirouBagui** [samszo/THYP_19-20#10]
Bonjour tout le monde,

Je me suis bloqué dans l'injection des données dans mon CV, j'utilise d3.js.

Je vous remercie pour le partage des pistes qui va m'aider à injecté les données dans mon CV .

**Comment by SofianeHadjadj** [comment]
@MirouBagui tu es bloqué dans la récupération des données du premier formulaire (nom, prénom...) ?

**Comment by MirouBagui** [comment]
@SofianeHadjadj J'ai récupérer les données mais j'arrive pas à les injectées dans mon Body.
j'ai pu injectée les noms prénoms mais il me reste le problem des photos et compétences.

**Comment by MirouBagui** [comment]
mission accomplished
